directive := command | command operator expression ｜ (directive) operator
operator := logical_operator
logical_operator := '//' | '\\' | '><' | '<' | '<=' | '==' | '>=' | '>'
math_operator := '/' | '*' | '+' | '-'
expression := float | command

command := command_name | command_name : arguments
command_name := main_command_name | main_command_name.sub_command_name
main_command_name := alphabets
sub_command_name := alphabets

arguments := argument | argument , arguments
argument := empty_string | string | ( directive )
